"""
listings/urls.py

Airbnb Clone — LISTINGS APP (URL routing)
============================================================================
Wires PropertyViewSet, PropertyImageViewSet (nested), and the reference-data
viewsets (categories/amenities) from views.py into routable URLs.

Requires:
    pip install drf-nested-routers
    (gives us NestedDefaultRouter so /properties/{property_pk}/photos/{id}/
     works without hand-writing path() entries for it)

Mount this in your project's root urls.py with, e.g.:
    path('api/', include('listings.urls')),
============================================================================
"""

from rest_framework.routers import DefaultRouter
from rest_framework_nested.routers import NestedDefaultRouter

from . import views

# ---------------------------- Top-level resources ---------------------------------------------------
router = DefaultRouter()
router.register('properties', views.PropertyViewSet, basename='property')
router.register('categories', views.PropertyCategoryViewSet, basename='category')
router.register('amenity-categories', views.AmenityCategoryViewSet, basename='amenity-category')
router.register('amenities', views.AmenityViewSet, basename='amenity')

# -------------------------- Nested resource: /properties/{property_pk}/photos/{id}/ -------------------
properties_router = NestedDefaultRouter(router, 'properties', lookup='property')
properties_router.register('photos', views.PropertyImageViewSet, basename='property-photos')

urlpatterns = router.urls + properties_router.urls

# ----------------------------------------------------------------------------
# Resulting endpoints (auto-generated by the routers above):
#
#   GET/POST      /properties/
#   GET/PUT/PATCH/DELETE  /properties/{id}/
#   GET            /properties/map/
#   GET            /properties/mine/
#   POST           /properties/{id}/publish/
#   POST           /properties/{id}/archive/
#   POST           /properties/{id}/images/
#   GET            /properties/{id}/availability/
#   POST           /properties/{id}/availability/bulk-update/
#
#   GET/PATCH/DELETE  /properties/{property_pk}/photos/{id}/
#
#   GET/POST      /categories/               GET/PUT/PATCH/DELETE /categories/{id}/
#   GET           /amenity-categories/        GET /amenity-categories/{id}/
#   GET/POST      /amenities/                 GET/PUT/PATCH/DELETE /amenities/{id}/
# ----------------------------------------------------------------------------